Oidc.FE/Models/ErrorViewModel.cs
namespace Oidc.FE.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Oidc.FE/Models/Requests/AuthRequest.cs
namespace Oidc.FE.Models.Requests;

public class AuthRequest
{
    public string? client_id { get; set; }
    public string? redirect_uri { get; set; }
    public string? response_type { get; set; }
    public string? scope { get; set; }
    public string? state { get; set; }
    public string? nonce { get; set; }
}

Oidc.FE/Models/Requests/UserLoginRequest.cs
namespace Oidc.FE.Models.Requests;

public class UserLoginRequest
{
    public string? Username { get; set; }
    public string? Password { get; set; }
}

Oidc.FE/Models/Responses/QrCodeDataResponse.cs
namespace Oidc.FE.Models.Responses;

public class QrCodeDataResponse
{
    public string? QrCodeImageAsBase64 { get; set; }
    public string? ImageType { get; set; }
}

Oidc.FE/Controllers/AuthorizeController.cs
using Microsoft.AspNetCore.Mvc;
using Oidc.FE.Models.Requests;
using Oidc.FE.Services.Auth;

namespace Oidc.FE.Controllers;

public class AuthorizeController : Controller
{ 
    private readonly IAuthService _authService;

    public AuthorizeController(IAuthService authService)
    {
        _authService = authService;
    }

    public IActionResult Index([FromQuery] AuthRequest authRequest)
    {
        var response = _authService.GenerateLoginWithQrCodePage(authRequest).Result;

        TempData["qrCodeImageAsBase64"] = response.QrCodeImageAsBase64;
        TempData["imgType"] = response.ImageType;

        return View();
    }

    [HttpGet]
    public IActionResult ClientLoginWithoutQrCode()
    {
        return View();
    }

    [HttpPost]
    public IActionResult ClientLoginWithoutQrCode(UserLoginRequest userLoginRequest)
    {
        // TODO: Call BE for get token => return token in redirect uri

        // Fake token
        var id_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c";

        return Redirect($"https://localhost:7776/Home/Privacy#{id_token}");
    }
}

Oidc.FE/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Oidc.FE.Models;
using System.Diagnostics;

namespace Oidc.FE.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Oidc.FE/Views/Authorize/ClientLoginWithoutQrCode.cshtml
@model Oidc.FE.Models.Requests.UserLoginRequest
@{
    ViewData["Title"] = "ClientLoginWithoutQrCode";
}

<h1>ClientLoginWithoutQrCode</h1>

<form method="post">
    <label asp-for="Username">Username:</label>
    <input asp-for ="Username" />

    <label asp-for="Password">Password:</label>
    <input asp-for="Password" />

    <button type="submit">Login</button>
</form>

Oidc.FE/Views/Authorize/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1>Login with QR Code</h1>

    <img alt="Embedded QR Code" style="width: 150px; height: 150px;" src="data:image/@TempData["imageType"];base64, @Html.Raw(TempData["qrCodeImageAsBase64"])" />

    <a asp-controller="Authorize" asp-action="ClientLoginWithoutQrCode">...Or click here to bypass QR Code</a>
</div>

Oidc.FE/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Oidc.FE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Oidc.FE</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Oidc.FE.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Oidc.FE</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Oidc.FE - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>